### PR TITLE
Fix Letterboxd login form submission

### LINKED ISSUE #20: Letterboxd login page web component changes
The login page for Letterboxd has changed, so EmBoxd is no longer authenticating successfully via Playwright browser automation.

### PR DESCRIPTION
**Pull request by vmasmitja**
Letterboxd login was failing due to Playwright timeouts when clicking the submit button, likely caused by Cloudflare overlays or dynamic page behavior.

This change submits the login form by sending an Enter key press from the password field instead of clicking the submit button. This approach is more robust and avoids interaction issues.

Additionally, the login flow now waits for network idle state before checking for the logged-in body class.

This fixes recurring `playwright: timeout exceeded` errors during authentication.

### CODE REVIEW

**Comment by computer-geek64** [comment]
Thanks so much for your changes! I apologize, this project has entered a somewhat dead state as I have not been very active in its maintenance in recent months. I do plan to be more heavily involved moving forward.

**Comment by computer-geek64** [comment]
Looking deeper into current issues, you're definitely right that the webpage has changed its HTML/CSS components so the current web automation is failing in a few areas.
Would love to get this change merged soon and repair the project back into a functional state ASAP

File: letterboxd/auth.go [hunk 1]
```diff
@@ -16,7 +16,7 @@ func (u User) isLoggedIn(page ...playwright.Page) bool {
 		defer page[0].Close()
 	}
 
-	var classes, err = page[0].Locator("body").GetAttribute("class")
```
Comment (computer-geek64) [inline letterboxd/auth.go:19]: Could we please keep the `var` for new variable declaration? (here as well as the other spots in this PR) The convention for this project is to use `var` when creating variables explicitly, and only to use the short assignment operator `:=` with if, for, switch, and other inline conditional statements.

I think it makes it clearer even for people not as familiar with golang, as it shares similarities with many other languages.

Nevertheless, regardless of which convention the project uses, I think it's most important to keep it all consistent - we shouldn't mix and match both styles here, so would definitely prefer we stick with `var` (specifically for initial variable assignment) as that's what the rest of the project is already doing.

File: letterboxd/auth.go [hunk 2]
```diff
@@ -40,13 +40,27 @@ func (u User) Login() {
 	if err := page.Locator("input#field-password").Fill(u.password); err != nil {
 		panic(err)
 	}
-	if err := page.Locator("input.js-remember").Check(); err != nil {
+
+	// Remember me (optional, ignore errors)
+	_ = page.Locator("input.js-remember").Check()
```
Comment (computer-geek64) [inline letterboxd/auth.go]: I agree that this need not be a fatal error

Can we instead use a warning log? I think this is a good middle ground - we still get visibility on failures here, but it should proceed normally even if it fails

Also I think there's no real need to add the preceding comment, the code is quite clear here

File: letterboxd/auth.go [hunk 3]
```diff
@@ -40,13 +40,27 @@ func (u User) Login() {
...
+
+	// SUBMIT VIA ENTER (robust, avoids overlays / cloudflare issues)
+	if err := page.Locator("input#field-password").Press("Enter"); err != nil {
```
Comment (computer-geek64) [inline letterboxd/auth.go:46]: Yep, definitely nicer to use form submission here! Thanks

Can we remove the comment here? Code is still verbose enough to understand logic flow in my opinion

File: letterboxd/auth.go [hunk 4]
```diff
@@ -40,13 +40,27 @@ func (u User) Login() {
...
 		panic(err)
 	}
-	if err := page.Locator("div.formbody > div.formrow > button[type=submit]").Click(); err != nil {
+
+	// Wait for navigation / login completion
+	_ = page.WaitForLoadState(playwright.PageWaitForLoadStateOptions{
+		State: playwright.LoadStateNetworkidle,
+	})
+
+	// Confirm logged in
```
Comment (computer-geek64) [inline letterboxd/auth.go]: This is duplicated code, we already have this check below

File: letterboxd/auth.go [hunk 5]
```diff
@@ -40,13 +40,27 @@ func (u User) Login() {
...
+	_ = page.Locator("input.js-remember").Check()
+
+	// SUBMIT VIA ENTER (robust, avoids overlays / cloudflare issues)
+	if err := page.Locator("input#field-password").Press("Enter"); err != nil {
 		panic(err)
 	}
-	if err := page.Locator("div.formbody > div.formrow > button[type=submit]").Click(); err != nil {
+
+	// Wait for navigation / login completion
+	_ = page.WaitForLoadState(playwright.PageWaitForLoadStateOptions{
```
Comment (computer-geek64) [inline letterboxd/auth.go]: Was not aware such a feature existed, definitely a good addition!

No need to assign return value to `_` here, can simply call `page.WaitForLoadState(...)`

Also comment still  feels unnecessary - in my experience, it's good to leave comments where code is not as self-documenting, in places where the logic is somewhat obfuscated/difficult to follow

**Review by computer-geek64 — CHANGES_REQUESTED** [review]
Thanks again for your PR! Would love to merge this in once the requested changes are made :)

**Comment by vmasmitja** [comment]
I’m totally fine with the suggested changes.
If you prefer, feel free to adjust the style/details yourself — my main goal is improving the overall robustness of the login flow.
If you’d rather I handle the updates, just let me know and I’ll push them. :-)

File: letterboxd/auth.go (hunk 3 above)
Comment (vmasmitja) [reply letterboxd/auth.go:46]: Sure!

File: letterboxd/auth.go (hunk 2 above)
Comment (vmasmitja) [reply letterboxd/auth.go]: Yes. You’re right. I agree.

File: letterboxd/auth.go (hunk 4 above)
Comment (vmasmitja) [reply letterboxd/auth.go]: Ooops

File: letterboxd/auth.go (hunk 5 above)
Comment (vmasmitja) [reply letterboxd/auth.go]: You’re right, good point.
I’ll simplify the call and remove the comment. Thanks!

**Comment by computer-geek64** [comment]
Sounds good, I just added the changes!

**Comment by vmasmitja** [comment]
Awesome, thanks for the quick merge! Glad it was useful 🙌
